services:
  greg:
    build: ./annoyance
    restart: unless-stopped
    image: greg:latest
    env_file:
      - ./.env
    volumes:
      - ./annoyance/data:/app/data

  greg-is-my-slack-id:
    build: ./gregisyourslackid
    restart: unless-stopped
    image: gregisyourslackid
    env_file:
      - ./.env

  flastsm:
    build: ./flastsm
    restart: unless-stopped
    image: flastsm:latest
    env_file:
      - ./.env
